#!/usr/bin/env python3
# Date: 2025-09-16
# Version: 1.2.0
# Purpose: Add artists to a Spotify playlist based on a text file of artist names
# Usage: python add_to_playlist.py <artist_file.txt> [--dry-run] [--verbose]
# Input:
#   - Text file with one artist name per line
#   - Playlist configuration (via config.yaml or inline)
# Output:
#   - Adds tracks to a Spotify playlist, logs matches, or simulates if in dry-run mode
# Chat name: Spotify Playlist Artist Adder
# GPT Model: OpenAI gpt-4o
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT

"""
Purpose:
    Add scraped artist names to Spotify playlist(s) and handle backups.

Usage:
    ./add_to_playlist.py <filename> [--backup-only] [--dry-run] [--force] [--verbose]

Input:
    - Artist text file with one entry per line
    - Environment variables for Spotify credentials (client ID/secret)
    - Configured playlist info in config.yaml

Output:
    - Updated Spotify playlists or backups written to ./tmp-*

Date: 2025-09-16
Version: 2.1.1
Chat name: pilotlight-scraper
GPT Model: GPT-4
Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT
"""

import argparse
import os
import shutil
from datetime import datetime
from playlist_utils import init_spotify, load_config, backup_playlist, restore_playlist, update_playlist

def parse_args():
    parser = argparse.ArgumentParser(description="Update Spotify playlist from artist file.")
    parser.add_argument("filename", help="File with list of artist names")
    parser.add_argument("--backup-only", action="store_true", help="Only back up playlists")
    parser.add_argument("--dry-run", action="store_true", help="Simulate update, write to ./tmp-* files")
    parser.add_argument("--force", "-f", action="store_true", help="Overwrite existing backup files")
    parser.add_argument("--verbose", action="store_true", help="Print detailed progress")
    return parser.parse_args()

args = parse_args()
config = load_config()

now = datetime.now().strftime("%Y-%m-%d_%H%M")

if args.backup_only or args.dry_run:
    sp = init_spotify()
    for playlist_cfg in config["playlists"]:
        title = playlist_cfg["title"]
        backup_file = f"{playlist_cfg['file']}-{now}.csv"

        if os.path.exists(backup_file) and not args.force:
            base, ext = os.path.splitext(backup_file)
            counter = 1
            while os.path.exists(f"{base}-{counter}{ext}"):
                counter += 1
            backup_file = f"{base}-{counter}{ext}"

        if args.verbose or args.dry_run:
            print(f"{'[DRY RUN] ' if args.dry_run else ''}Backing up: {title} ➔ {backup_file}")

        if args.dry_run:
            backup_file = f"./tmp-{os.path.basename(backup_file)}"

        backup_playlist(sp, playlist_cfg["id"], backup_file)

    if args.backup_only:
        exit(0)

sp = init_spotify()

if args.dry_run:
    output_file = f"./tmp-{os.path.basename(args.filename)}"
else:
    output_file = args.filename

with open(args.filename) as f:
    artists = [line.strip() for line in f if line.strip()]

for playlist_cfg in config["playlists"]:
    update_playlist(sp, artists, playlist_cfg, output_file, dry_run=args.dry_run, verbose=args.verbose)
