playlists:
  archives:
    2025-Q2:
      id: 55IZDTdssMhPSFwPfLbTWF
      name: 'Pilot Light Archive: 2025-Q2'
    2025-Q3:
      id: 1Zt3MAv81tsBnzUCSs0aKi
      name: 'Pilot Light Archive: 2025-Q3'
  recent:
    id: 3ClD58fHAbKgGdfkSakapT
    name: 'Pilot Light Playlist: Recent Shows'
  upcoming:
    id: 2wxY4VF3AC3IVmnqldUHiy
    name: 'Pilot Light Playlist: Upcoming Shows'
