#!/usr/bin/env python3
# Date: 2025-09-17
# Version: 1.0.1
# Purpose: List all Spotify playlists for authenticated user (with persistent cache)
# Usage: ./get_playlist_ids.py
# Input: None
# Output: Prints playlist names and IDs
# Chat name: get-playlist-ids
# GPT Model: OpenAI o4-mini
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT

import os
import spotipy
from spotipy.oauth2 import SpotifyOAuth

# PATCH: persistent cache
os.makedirs(".cache", exist_ok=True)
os.environ["SPOTIPY_CACHE_PATH"] = os.path.join(".cache", ".spotify_oauth_cache")

def init_spotify():
    return spotipy.Spotify(auth_manager=SpotifyOAuth(scope="playlist-read-private"))

def main():
    sp = init_spotify()
    results = sp.current_user_playlists()
    for item in results["items"]:
        print(f"{item['name']}:\n  ID: {item['id']}\n")

if __name__ == "__main__":
    main()
