#!/usr/bin/env python3
# Date: 2025-09-17
# Version: 1.0.0
# Purpose: Fetch Spotify user ID and playlists, printing config-ready YAML for use in PilotLight scripts
# Usage: python get_playlist_ids.py [--verbose]
# Input: Requires SPOTIPY_CLIENT_ID, SPOTIPY_CLIENT_SECRET, and SPOTIPY_REDIRECT_URI as env vars or in .env
# Output: Prints user ID and playlists as YAML block to stdout
# Chat name: get_playlist_ids
# GPT Model: OpenAI o4-mini
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT

import os
import spotipy
import argparse
import yaml
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv

def init_spotify():
    load_dotenv()  # loads SPOTIPY_* vars from .env if available
    return spotipy.Spotify(auth_manager=SpotifyOAuth(scope="playlist-read-private"))

def fetch_playlists(sp, verbose=False):
    user_id = sp.current_user()["id"]
    if verbose:
        print(f"# Spotify user ID: {user_id}")
    playlists = sp.current_user_playlists()
    out = {
        "user_id": user_id,
        "playlists": {}
    }
    for p in playlists["items"]:
        name = p["name"]
        pid = p["id"]
        if verbose:
            print(f"# {name} → {pid}")
        out["playlists"][name] = {"name": name, "id": pid}
    return out

def main():
    parser = argparse.ArgumentParser(description="Print Spotify playlists in YAML format")
    parser.add_argument("--verbose", "-v", action="store_true", help="Show more info while running")
    args = parser.parse_args()

    sp = init_spotify()
    data = fetch_playlists(sp, args.verbose)
    print("\n# Config-ready YAML block:\n")
    print(yaml.dump(data["playlists"], sort_keys=False))

if __name__ == "__main__":
    main()
