#!/usr/bin/env python3
# ============================================================================
# Script:       history_utils.py
# Version:      1.1.0
# Date:         2026-03-01
# Purpose:      Show history management and archive playlist logic
#
# Maintains a cumulative show_history.csv seeded from existing scraped
# files.  Provides functions to split history into a rolling "recent"
# window (90 days) and completed archive quarters, and to auto-create
# Spotify archive playlists.
#
# Usage:        Imported by create_pilotlight_playlist.py
# Input:        Scraped CSVs, pipe-delimited text files, config.yaml
# Output:       show_history.csv, archive playlist entries in config.yaml
#
# Requirements:
#   - spotipy, pyyaml
#
# Session:      Archive Playlists and Rolling Recent Window
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

import csv
import glob
import logging
import os
from datetime import date, timedelta

import yaml

log = logging.getLogger("pilotlight")

HISTORY_FILE = "show_history.csv"


def date_to_quarter(d):
    """Convert a date to its calendar quarter label.

    >>> date_to_quarter(date(2025, 8, 15))
    '2025-Q3'
    """
    q = (d.month - 1) // 3 + 1
    return f"{d.year}-Q{q}"


def quarter_date_range(label):
    """Return (start, end) dates for a quarter label like '2025-Q3'.

    >>> quarter_date_range('2025-Q3')
    (datetime.date(2025, 7, 1), datetime.date(2025, 9, 30))
    """
    year, qstr = label.split("-")
    year = int(year)
    q = int(qstr[1])
    start_month = (q - 1) * 3 + 1
    start = date(year, start_month, 1)
    # End of quarter: first day of next quarter minus one day
    if q < 4:
        end = date(year, start_month + 3, 1) - timedelta(days=1)
    else:
        end = date(year + 1, 1, 1) - timedelta(days=1)
    return start, end


def load_history(path=HISTORY_FILE):
    """Read show_history.csv and return list of dicts with keys:
    date, artist, price.  Returns empty list if file doesn't exist."""
    if not os.path.exists(path):
        return []
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def _write_history(rows, path):
    """Write history rows to CSV, sorted by date then artist."""
    rows.sort(key=lambda r: (r["date"], r["artist"].upper()))
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["date", "artist", "price"])
        writer.writeheader()
        writer.writerows(rows)


def _parse_pipe_file(filepath):
    """Parse pipe-delimited text file into list of dicts.

    Format: "YYYY-MM-DD | ARTIST1, ARTIST2 | $PRICE"
    Multi-artist lines are split into one row per artist.
    """
    rows = []
    with open(filepath, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = [p.strip() for p in line.split("|")]
            if len(parts) < 3:
                log.warning("Skipping malformed pipe line: %s", line)
                continue
            show_date = parts[0]
            artists_str = parts[1]
            price_str = parts[2].lstrip("$").strip()
            if price_str.upper() == "FREE":
                price_str = "FREE"
            for artist in artists_str.split(", "):
                artist = artist.strip()
                if artist:
                    rows.append({
                        "date": show_date,
                        "artist": artist,
                        "price": price_str,
                    })
    return rows


def seed_history(path=HISTORY_FILE):
    """Seed show_history.csv from all available historical data files.

    Reads:
    - upcoming-artists_*.csv (CSV format: date,artist,price)
    - recent_artists_all.txt (pipe format)
    - upcoming_artists_all.txt (pipe format)

    Returns count of rows written.
    """
    all_rows = []

    # CSV files
    for csvfile in sorted(glob.glob("upcoming-artists_*.csv")):
        log.info("Seeding from CSV: %s", csvfile)
        with open(csvfile, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                all_rows.append({
                    "date": row["date"],
                    "artist": row["artist"],
                    "price": row["price"],
                })

    # Pipe-delimited files
    for txtfile in ["recent_artists_all.txt", "upcoming_artists_all.txt"]:
        if os.path.exists(txtfile):
            log.info("Seeding from pipe file: %s", txtfile)
            all_rows.extend(_parse_pipe_file(txtfile))

    # Deduplicate by (date, artist_upper)
    seen = set()
    deduped = []
    for row in all_rows:
        key = (row["date"], row["artist"].upper())
        if key not in seen:
            seen.add(key)
            deduped.append(row)

    _write_history(deduped, path)
    log.info("Seeded history with %d rows -> %s", len(deduped), path)
    return len(deduped)


def append_to_history(new_rows, path=HISTORY_FILE):
    """Append new rows to history, deduplicating by (date, artist_upper).

    If the history file doesn't exist, seeds it first from available
    historical data files, then appends any additional new rows.

    Returns count of new rows added.
    """
    if not os.path.exists(path):
        log.info("History file not found, seeding from available data...")
        seed_history(path)

    existing = load_history(path)
    seen = {(r["date"], r["artist"].upper()) for r in existing}

    added = 0
    for row in new_rows:
        key = (row["date"], row["artist"].upper())
        if key not in seen:
            seen.add(key)
            existing.append(row)
            added += 1

    if added > 0:
        _write_history(existing, path)
        log.info("Appended %d new rows to history (total: %d)",
                 added, len(existing))
    else:
        log.info("No new rows to add to history (total: %d)", len(existing))

    return added


def split_history(history_rows, today, recent_days=90):
    """Split history into recent rows and archive quarters.

    Parameters
    ----------
    history_rows : list of dict
        Each dict has keys: date, artist, price.
    today : date
        Reference date for splitting.
    recent_days : int
        Number of days for the rolling recent window (default 90).

    Returns
    -------
    recent_rows : list of dict
        Shows where today - recent_days <= date < today.
    archive_quarters : dict of str -> list of dict
        Keyed by "YYYY-QN".  Only includes quarters whose end date
        is before the recent window cutoff (fully aged out).
    """
    cutoff = today - timedelta(days=recent_days)
    recent_rows = []
    past_rows = []  # older than recent window

    for row in history_rows:
        try:
            show_date = date.fromisoformat(row["date"])
        except (ValueError, KeyError):
            log.warning("Skipping row with bad date: %s", row)
            continue
        # Exclude upcoming shows (date >= today)
        if show_date >= today:
            continue
        if show_date >= cutoff:
            recent_rows.append(row)
        else:
            past_rows.append(row)

    # Group past rows into quarters, but only include fully aged-out quarters
    archive_quarters = {}
    for row in past_rows:
        show_date = date.fromisoformat(row["date"])
        label = date_to_quarter(show_date)
        _, q_end = quarter_date_range(label)
        # Only archive quarters whose end date is before the cutoff
        if q_end < cutoff:
            archive_quarters.setdefault(label, []).append(row)

    return recent_rows, archive_quarters


def ensure_archive_playlist(sp, label, config, config_path, dry_run=False):
    """Ensure a Spotify archive playlist exists for the given quarter label.

    If config["playlists"]["archives"][label] already exists, returns it.
    Otherwise creates a new Spotify playlist and saves the ID to config.

    Returns dict with 'name' and 'id' keys.
    """
    archives = config["playlists"].setdefault("archives", {})

    if label in archives:
        log.info("Archive playlist exists: %s", archives[label]["name"])
        return archives[label]

    playlist_name = f"Pilot Light Archive: {label}"

    if dry_run:
        log.info("[DRY RUN] Would create Spotify playlist: %s", playlist_name)
        print(f"[DRY RUN] Would create Spotify playlist: {playlist_name}")
        return {"name": playlist_name, "id": "DRY-RUN"}

    # Create the playlist on Spotify
    user_id = sp.me()["id"]
    result = sp.user_playlist_create(user_id, playlist_name, public=True)
    playlist_id = result["id"]
    log.info("Created Spotify playlist: %s (id=%s)", playlist_name, playlist_id)
    print(f"Created Spotify playlist: {playlist_name}")

    # Save to config
    entry = {"name": playlist_name, "id": playlist_id}
    archives[label] = entry
    with open(config_path, "w", encoding="utf-8") as f:
        yaml.dump(config, f, default_flow_style=False)
    log.info("Saved archive playlist ID to %s", config_path)

    return entry


# ---- Playlist descriptions ----

_VENUE_BLURB = (
    "The Pilot Light is an intimate live music venue in Knoxville, TN "
    "known for indie, punk, and experimental music."
)

_DESCRIPTIONS = {
    "upcoming": (
        f"{_VENUE_BLURB} "
        "This playlist features top Spotify tracks from artists with "
        "upcoming shows. Updated weekly. "
        "Also check out our Recent Shows and quarterly Archive playlists -- "
        "search Spotify for \"Pilot Light\" to find them all."
    ),
    "recent": (
        "Top tracks from artists who recently played The Pilot Light "
        "(Knoxville, TN), rolling 90-day window. Updated weekly. "
        "Also check out our Upcoming Shows and quarterly Archive playlists -- "
        "search Spotify for \"Pilot Light\" to find them all."
    ),
}


def _archive_description(label):
    """Build a description string for an archive quarter playlist."""
    start, end = quarter_date_range(label)
    start_str = start.strftime("%B %Y")
    end_str = end.strftime("%B %Y")
    return (
        f"Artists who played The Pilot Light (Knoxville, TN) from "
        f"{start_str} to {end_str}. "
        f"{_VENUE_BLURB} "
        "Also check out our Upcoming Shows and Recent Shows playlists -- "
        "search Spotify for \"Pilot Light\" to find them all."
    )


def update_playlist_descriptions(sp, config, archive_quarters=None,
                                 dry_run=False):
    """Set descriptions on all managed playlists.

    Updates upcoming, recent, and any archive playlists with informational
    text about the venue and cross-references to related playlists.
    """
    prefix = "[DRY RUN] " if dry_run else ""

    # Upcoming and recent
    for key, desc in _DESCRIPTIONS.items():
        playlist_cfg = config["playlists"].get(key)
        if not playlist_cfg or not playlist_cfg.get("id"):
            continue
        log.info("%sSetting description on: %s", prefix, playlist_cfg["name"])
        if not dry_run:
            sp.playlist_change_details(playlist_cfg["id"], description=desc)

    # Archive playlists
    archives = config["playlists"].get("archives", {})
    for label, acfg in archives.items():
        if not acfg.get("id") or acfg["id"] == "DRY-RUN":
            continue
        desc = _archive_description(label)
        log.info("%sSetting description on: %s", prefix, acfg["name"])
        if not dry_run:
            sp.playlist_change_details(acfg["id"], description=desc)
