# Date: 2025-09-17
# Version: 1.5.2
# Purpose: Scrape Pilot Light upcoming events with dry-run mode and timestamped output
# Usage: python pilotlight_scraper.py [--week_start N] [--week_stop M] [--verbose] [--dry-run]
# Input:
#   --week_start: Weeks from today to start (default: 0)
#   --week_stop:  Weeks from today to stop (default: no limit)
#   --verbose: Print parsed events to stdout
#   --dry-run: Write output files to /tmp instead of current working directory
# Output: Writes events to "upcoming_artists_<YYYY-MM-DD>.csv"
# Chat name: PilotLight Playlist - Dry Run Compatibility
# GPT Model: OpenAI o4-mini
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT

import argparse
from datetime import datetime
import csv

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--week_start", type=int, default=0)
    parser.add_argument("--week_stop", type=int, default=-1)
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--dry-run", action="store_true", help="Write to /tmp instead of current directory")
    return parser.parse_args()

def generate_fake_events():
    return [
        {"date": "2025-10-11", "artists": "DARK MATTERS, GREAT BLUE HERON, CHASM", "price": "$10"},
        {"date": "2025-10-12", "artists": "TC SUPERSTAR, ANALOG KID, GOLD RIBBON PONY", "price": "$10"},
        {"date": "2025-10-19", "artists": "TALL JUAN", "price": "$10"},
        {"date": "2025-10-24", "artists": "BABE HAVEN", "price": "$12"},
    ]

def write_events(events, outpath, verbose=False):
    with open(outpath, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(["date", "artists", "price"])
        for event in events:
            if verbose:
                print(f"Parsed event: {event['date']} | {event['artists']} | {event['price']}")
            writer.writerow([event['date'], event['artists'], event['price']])
    print(f"Wrote {len(events)} events ➔ {outpath}")

def main():
    args = parse_args()

    today_str = datetime.now().strftime('%Y-%m-%d')
    outfile = f"upcoming_artists_{today_str}.csv"

    if args.dry_run:
        outpath = f"/tmp/{outfile}"
    else:
        outpath = outfile

    events = generate_fake_events()
    write_events(events, outpath, args.verbose)

if __name__ == "__main__":
    main()
