# playlist_utils.py
# Purpose: Utilities for loading config, Spotify auth, backups, and playlist updates
# Usage: Imported by create_pilotlight_playlist.py
# Input: YAML config, scraped artist data
# Output: Playlist updates or dry-run logs
# Date: 2025-09-17
# Version: 1.5.4
# Chat name: PilotLightPlaylist
# GPT Model: GPT-4
# Attribution: Generated by Michael Gilchrist in collaboration with ChatGPT

import os
from dotenv import load_dotenv 
load_dotenv()                  
import yaml
import spotipy
import csv
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv

load_dotenv()

def init_spotify():
    return spotipy.Spotify(auth_manager=SpotifyOAuth(
        scope="playlist-modify-public playlist-modify-private",
        cache_path=os.path.expanduser("~/.cache/spotify_token.json")
    ))

def load_config():
    with open("config.yaml", "r") as f:
        return yaml.safe_load(f)

def backup_playlist(sp, playlist_id, output_file):
    tracks = []
    results = sp.playlist_items(playlist_id)
    while results:
        for item in results["items"]:
            track = item["track"]
            if track:
                artist_names = ", ".join(a["name"] for a in track["artists"])
                tracks.append(f"{artist_names},{track['name']},{track['uri']}")
        if results["next"]:
            results = sp.next(results)
        else:
            break
    with open(output_file, "w") as f:
        f.write("Artist,Title,URI\n")
        f.write("\n".join(tracks))

def restore_playlist(sp, playlist_id, uris):
    sp.playlist_replace_items(playlist_id, uris[:100])
    for i in range(100, len(uris), 100):
        sp.playlist_add_items(playlist_id, uris[i:i + 100])

def search_track(sp, artist, title):
    query = f"artist:{artist} track:{title}"
    results = sp.search(q=query, type="track", limit=1)
    tracks = results.get("tracks", {}).get("items", [])
    if tracks:
        return tracks[0]["uri"]
    return None

def update_playlist(sp, artists, playlist_cfg, output_file, dry_run=False, verbose=False):
    found_tracks = []
    print(f"{'[DRY RUN] ' if dry_run else ''}Searching for tracks for: {playlist_cfg['name']}")
    print("  Not found: Artist,Title,URI")

    for row in artists:
        if isinstance(row, str):
            parts = row.split(",", 2)
        else:
            parts = row

        if len(parts) < 2:
            continue

        artist = parts[0].strip()
        title = parts[1].strip()
        uri = parts[2].strip() if len(parts) == 3 else ""

        if uri.startswith("spotify:track:"):
            found_tracks.append(uri)
            if verbose:
                print(f"{'[DRY RUN] ' if dry_run else ''}Using provided URI: {uri} for {artist} - {title}")
        else:
            result_uri = search_track(sp, artist, title)
            if result_uri:
                found_tracks.append(result_uri)
            else:
                print(f"  Not found: {artist},{title},{uri}")

    if dry_run:
        print(f"[DRY RUN] Would update {playlist_cfg['name']} with {len(found_tracks)} tracks.")
    else:
        restore_playlist(sp, playlist_cfg["id"], found_tracks)
        print(f"Updated {playlist_cfg['name']} with {len(found_tracks)} track(s).")

    with open(output_file, "w") as f:
        for uri in found_tracks:
            f.write(f"{uri}\n")
