#!/usr/bin/env bash
# ============================================================================
# Script:       run_pilotlight_cron.sh
# Version:      1.0.0
# Date:         2026-02-17
# Purpose:      Cron wrapper for PilotLight Playlist updater
#
# Runs the playlist scraper/updater in a cron-safe environment.  Starts in
# --dry-run mode by default -- remove the flag once you've verified output.
#
# Usage:        run_pilotlight_cron.sh [OPTIONS]
# Input:        None (reads .env and config.yaml from repo directory)
# Output:       Log file in logs/cron_YYYY-MM-DD.log
#
# Options:
#   -n, --dry-run   Pass --dry-run to the Python script (default: on)
#   -v, --verbose   Pass --verbose to the Python script
#   -h, --help      Show this help message
#
# Cron entry (Monday 8am on obed):
#   0 8 * * 1 /home/mikeg/Repositories/PilotLightPlaylist/run_pilotlight_cron.sh
#
# Requirements:
#   - Python 3.10+ with deps installed (or venv at ./venv)
#
# Session:      PilotLight Playlist Fixes
# AI Model:     Claude Opus 4.6
# Attribution:  Generated by Michael Gilchrist in collaboration with
#               ClaudeAI Opus 4.6
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ---- Configuration ----
# Remove --dry-run below once you've verified cron output is correct
DRY_RUN="--dry-run"
VERBOSE="--verbose"
DEBUG=""

# ---- Help ----
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    sed -n '2,/^# ====/{ /^# ====/d; s/^# //; s/^#$//; p }' "$0"
    exit 0
fi

# ---- Logging ----
mkdir -p logs
LOG_FILE="logs/cron_$(date +%Y-%m-%d).log"

{
    echo "==== PilotLight Cron Run: $(date) ===="

    # ---- Load environment ----
    if [[ -f .env ]]; then
        set -a
        # shellcheck source=/dev/null
        source .env
        set +a
    fi

    # ---- Activate virtualenv if present ----
    if [[ -f venv/bin/activate ]]; then
        # shellcheck source=/dev/null
        source venv/bin/activate
    fi

    # ---- Run the updater ----
    python3 create_pilotlight_playlist.py $DRY_RUN $VERBOSE $DEBUG 2>&1

    echo "==== Completed: $(date) ===="

} >> "$LOG_FILE" 2>&1
